### ISSUE TITLE
PTF keeps giving database error after 1-3 hours of running

### ISSUE THREAD

**Issue by vincev1975** [mehtadone/PTFeeder#239] opened 2018-03-05 01:10 UTC
I get this series of errors after running the latest version of PTF for 1-3 hours.  It is very consistent.  Please fix this issue.  I have to restart it constantly.
https://www.screencast.com/t/OXkUdry149

**Comment by bgreater** [comment] 2018-03-05 07:07
I'm getting the same thing and it's on start up. So basically PT feeder never sets the correct PT settings. I'm having to essentially just run PT without PT Feeder. It just started happening in the last 24 hours.

![screenshot 2018-03-05 02 05 47](https://user-images.githubusercontent.com/152350/36961534-d94d0da8-2019-11e8-8ed0-15055fe87888.png)

**Comment by bgreater** [comment] 2018-03-05 07:08
I've tried deleting the DB and nothing works

**Comment by vincev1975** [comment] 2018-03-05 14:20
I am getting this error Could not update database right from the start after restarting PTF.  I deleted DB and  restarted only to get the same error.  Please fix for next release.  This is a crucial bug.
https://www.screencast.com/t/MRHjUxadj

**Comment by XXoltriXX** [comment] 2018-03-05 15:01
Hi,

Two of my bots constantly gives me the same error (Both Bitttrex):

![image](https://user-images.githubusercontent.com/36410192/36981621-5053a746-2096-11e8-8096-e341c9bba351.png)

I removed the PTFeeder DB, and even removed my data files for PT, i still get this error no matter what i do.
The bots now stays in super-bear, because of this issue...

**Comment by XXoltriXX** [comment] 2018-03-05 15:31
now i also get this on Binance...

![image](https://user-images.githubusercontent.com/36410192/36983413-f89a3858-209a-11e8-82dc-bfa6b5d9606d.png)

**Comment by bgreater** [comment] 2018-03-06 02:57
@mehtadone any ideas here? I've tried this on window server 13 and windows 10 and both give the same results, always the same exception. I've tried all of the steps below but nothing worked

1. Stop PT Feeder. Delete the ptfeeder.db file in the database directory of PT Feeder. Restart feeder.
2. If 1 does not work, check your time and timezone. A tool to help windows users to do this is provided in Common error number 3.
3. If 1 and 2 do not work, make sure the database file is not in read only mode. This Youtube video describes how.
4. Set CalculateTrailingValues as false in hostsettings.json. In appsettings.json, change MaxTrailingProfit to TrailingProfit and MaxTrailingBuy to TrailingBuy. Follow step 1 again and restart feeder.
5. Try downgrading from 1.4.0 to 1.3.5. This has slightly different database handling.

**Comment by XXoltriXX** [comment] 2018-03-06 04:25
I still have the same issues, none of my bots are working correctly! How do we resolve this asap??????? Is there no interim fix for this issue? The bots are not working at all, it also chooses the wrong market condition (Stuck in superbear) thus redering PT Feeder absolutely useless at the moment, i might as well just switch them off and pray i dont loose any money in the meantime. Can we please have an indication as to what the issue is and when we can expect a fix please?

![image](https://user-images.githubusercontent.com/36410192/37013976-179689d0-2106-11e8-9285-4404fda53952.png)

**Comment by dorjedan** [comment] 2018-03-06 04:31
I also have this issue. Since the other suggestions didn't work, downgrading to 1.3.5 solves the issue for now.

**Comment by bgreater** [comment] 2018-03-06 15:28
Using version 1.3.5 still doesn't work for me as it can't calculate the Top Coin change
![screenshot 2018-03-06 10 27 37](https://user-images.githubusercontent.com/152350/37040998-1e5ddcbe-2129-11e8-9a86-79cd57611145.png)

I'm gonna check out PT magic as a PT feeder alternative

**Comment by ironc0in** [comment] 2018-03-06 17:45
I'm getting the same, i believe it's a good idea to keep PT-Magic installed and preconfigured as backup as downtime is not an option.

**Comment by mehtadone** [comment] 2018-03-06 20:38
https://github.com/mehtadone/PTFeeder/releases/tag/pt-feeder-v1.4.0.457

Closing as duplicate of https://github.com/mehtadone/PTFeeder/issues/237

**Closed by mehtadone** 2018-03-06 20:38 UTC
