### ISSUE TITLE
Error in Top coins average change - BTC_USDT - Binance

### ISSUE THREAD

**Issue by DavidBriongos** [mehtadone/PTFeeder#234] opened 2018-03-03 11:48 UTC
When I use PT Feeder only with pair BTC_USDT on Binance, I put the parameter "TopCurrenciesToCheck": 1", because I want only check pair BTC_USDT, but it don't work. The bot always indicates 0%.

Thank you!

**Comment by mehtadone** [comment] 2018-03-03 18:57
Hey @DavidBriongos, this is fixed in the version coming out this week. Closing this as a duplicate of https://github.com/mehtadone/PTFeeder/issues/218 but that one will stay open until the release

**Closed by mehtadone** 2018-03-03 18:57 UTC

**Comment by kolesnikow** [comment] 2018-03-17 19:20
I have still this issue after updating to pt-feeder-v1.4.0.459 and deleting the database

**Comment by mehtadone** [comment] 2018-03-17 19:24
@kolesnikow this fix hasn't been released yet. It will be in v1.4.1 which is going into beta this week
