### ISSUE TITLE
My ptfeeder freezing/dont react.

### ISSUE THREAD

**Issue by cadaisles** [mehtadone/PTFeeder#238] opened 2018-03-04 19:03 UTC
Firstly sorry for my bad english.
My pt feeder starting and everything is normal. İts working very well.
But after 2 or 3 hours my pt-feeder freezing and dont react markets situtation.
No checking  , overriding dont do anything.And my settings fucked up.
Any idea here for this issue ?

**Comment by mehtadone** [comment] 2018-03-04 20:50
What do you mean by freezing? Can you send me the log file?

**Comment by cadaisles** [comment] 2018-03-05 05:28
[ptfeeder-20180304.log](https://github.com/mehtadone/PTFeeder/files/1779594/ptfeeder-20180304.log)

Sure.Thanks for support.Freezing i mean pt-feeder stoped.U can see in logfile stop time.
2018-03-04 17:57:06.850 +03:00

**Comment by mehtadone** [comment] 2018-03-06 20:37
https://github.com/mehtadone/PTFeeder/releases/tag/pt-feeder-v1.4.0.457

Closing as duplicate of https://github.com/mehtadone/PTFeeder/issues/237

**Closed by mehtadone** 2018-03-06 20:37 UTC
