### ISSUE TITLE
Volatility Readings ends up at +1.5% for all pairs

### ISSUE THREAD

**Issue by a02460** [mehtadone/PTFeeder#131] opened 2018-02-09 03:00 UTC
After running PT 1.3.5.329, The database doesn't seem to update the volatility readings and they all end up normalising at 1.5% (both up and downside). I had to delete the database file and restart the PT feeder for it to work properly on that portion again.

**Comment by mehtadone** [comment] 2018-02-09 20:58
I've managed to repro this. Will get a fix in soon

**Comment by Gitulu** [comment] 2018-02-12 08:53
Hello Mehtadone,

I can confirm this issue the volatility is after a time for all pair the same in version: "1.3.5.329".
Attached you will find the log in debug mode, maybe this will help you.

![vol](https://user-images.githubusercontent.com/35115314/36089098-6ee28460-0fda-11e8-88f1-1dd223256b53.png)

Please let me know if you need anything else.

[PTFeeder-20180212.log](https://github.com/mehtadone/PTFeeder/files/1715753/PTFeeder-20180212.log)

Cheers

**Comment by damajicman3** [comment] 2018-02-14 16:35
![volatility issue](https://user-images.githubusercontent.com/32244880/36215783-08aea1fe-117b-11e8-9d7d-2b1e12bf1519.PNG)

every pair/coin shows up with the same volatility for upside and downside. I had to exclude those functions for feeder not to apply my offsets for every pair.

**Comment by damajicman3** [comment] 2018-02-14 16:36
every pair was showing up with -0.5% upside and -1% downside. has been like this for around 10 hours now randomly. i just noticed this once i cleared a BIG BAG lol.

**Comment by damajicman3** [comment] 2018-02-14 19:05
could this be because i may have been banned?

**Comment by mehtadone** [comment] 2018-02-14 19:18
No there is a bug in the current version for upside and downside volatility. There should be a new version out in the next couple of days. Few options: 

1. PM on discord if you want the beta
2. Not use these for the time being
3. Downgrade to 1.3.4

Apologies about this

**Comment by fjdelaba** [comment] 2018-02-14 20:36
Thanks for the Reply man!

**Comment by Mtrade** [comment] 2018-02-20 02:09
I am experiencing static volatility at 0.3% for both the upside and downside as well. 

Can we still expect a fix for this shortly as planned, or has this now been moved to a 1.4 release? I'd prefer not to rollback to 1.3.4 if a fix is coming soon, but if a fix won't be deployed potentially for weeks then I will rollback. Thanks

**Comment by mehtadone** [comment] 2018-02-20 02:24
@Mtrade fix it tomorrow

**Comment by mehtadone** [comment] 2018-02-20 10:54
Fixed in 1.4. Remember to delete your database file first before update

**Comment by Mtrade** [comment] 2018-02-20 19:52
Thanks for the update, but it appears not to be working as intended. Upon first run, upside and downside volatility are generated but do not change for all pairs on consecutive cycles. Additionally it looks like these volatility calculations are not correct based on my understanding of the wiki. Could feeder be using a different period than that set in MinutesToMeasureTrend?

I did delete the database file before update, and once again to recheck but the problem persists.

**Comment by mehtadone** [comment] 2018-02-20 20:37
@Mtrade would you mind giving me an example? Maybe a snippet of your pairs.properties would be useful

**Comment by Mtrade** [comment] 2018-02-20 21:33
Ok, an example of one pair:

#------------------BTC/APPC------------------
# Last Price: 0.00006856
# Volume: 406.5719
# Price change (60): -3.42%
# Price change (720): -6.38%
# High/Low price change (60): -1.73%
# High/Low price change (720): -5.58%
# Upside volatility: 0.41%
# Downside volatility: 0.46%

APPCBTC_trading_enabled = true
APPCBTC_DCA_enabled = -8
APPCBTC_buy_strategy = EMASPREAD
APPCBTC_buy_value = -1.7625
APPCBTC_sell_value = 0.525
APPCBTC_trailing_profit = 0.2054
APPCBTC_trailing_buy = 0.2292
APPCBTC_max_cost = 0.002025
APPCBTC_min_buy_balance_percentage = 40
APPCBTC_min_buy_volume = 150
APPCBTC_min_buy_price = 0.000003
APPCBTC_buy_value_limit = 0
APPCBTC_max_buy_spread = 1
APPCBTC_min_profit = 0.55
#------------------------------------



The upside and downside volatility numbers have not changed since first run. The same is true for all other pairs (i.e. other pairs have their own volatility calculations, but do not change as well.)

As for the calculation issue, based on the wiki my understanding of the calculation would be as follows:
For upside volatility, assuming MinutesToMeasureTrend is 60:
Calculate [(High/Open - 1) * 100] for each 5 minute period, then take the average of this for the last 12 periods to end up with UpsideVolatility.

Let me know if you need more pairs file info. Thanks

**Comment by Mtrade** [comment] 2018-02-21 17:35
Tried running ver 1.3.4.236 and the same issue occurs, upside and downside volatility do not update.

**Comment by mehtadone** [comment] 2018-02-21 18:01
Ahh I understand now. In 1.3.5 they were the same for every coin. This is for each cycle. 

The volatility calculation takes time it doesnt check every pair cycle. The code actually has it for every 100th cycle. The more this is reduced, the longer it will take to do the calcualtions. 

There is an improvement coming in the next version, which may mean we can do the calc a lot quicker

**Closed by mehtadone** 2018-02-21 18:01 UTC

**Comment by mehtadone** [comment] 2018-02-21 18:02
Raised this issue to track that fix: https://github.com/mehtadone/PTFeeder/issues/193

**Comment by Mtrade** [comment] 2018-02-21 18:18
Ok, I assumed it was designed to calc every cycle. If this could be implemented it would be extremely helpful.

Can you confirm that feeder should be calculating volatility using the formula I posted above? It would help me to understand the exact calculation method for my internal testing.

Copied here again for reference:
_For upside volatility, assuming MinutesToMeasureTrend is 60:
Calculate [(High/Open - 1) * 100] for each 5 minute period, then take the average of this for the last 12 periods to end up with UpsideVolatility._

**Comment by mehtadone** [comment] 2018-02-21 18:51
@Mtrade, yes that is correct. The average price movement up
